Controllers films users
adrizhinskaya/java-filmorate pull request #5
Opened 2024-02-24 19:24 UTC by adrizhinskaya

2024-02-25 21:29 UTC, Yang-Pi requested changes
Общий комментарий - добавь логирование как ошибок, так и успешных операций вроде "Удачно создали фильм с {id}"

2024-02-25 21:29 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            int id = films.isEmpty() ? 1 : Collections.max(films.keySet()) + 1;
Генерацию id лучше вынести в отдельный метод вроде generateId, как это было для менеджера задач на прошлом проекте

2024-02-25 21:29 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } else if (films.containsKey(film.getId())) {
При текущей реализации возможен такой сценарий - пришла запись с каким-то рандомным id, этой записи у нас нет, поэтому сохраняется с этим рандомным id; выглядит как возможный источник проблем

в качестве легкого решения - для каждой записи всегда генерировать новый id и сохранять

2024-02-25 21:29 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
См комментарии к FilmController

2024-02-25 21:29 UTC, Yang-Pi commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        assert violations.isEmpty();
Рекомендую не сам валидатор тестировать, а то, что контроллер вернет статус-код об ошибке при неверных данных

2024-02-26 18:46 UTC, adrizhinskaya commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        assert violations.isEmpty();
Добавила новых тестов по проверке кодов состояния. Но они используют Mockito (единственный рабочий вариант, который я нашла). Однако наставник говорил не использовать моки и юзать Unit. Если вдруг, у Вас есть желание поделиться ссылочкой с полезными ресурсами по написанию тестов по API, буду очень признательна.

2024-02-27 15:35 UTC, Yang-Pi commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        assert violations.isEmpty();
Хорошо, понял тебя. Насчет материалов - в следующих спринтах будете подробно это разбирать как раз)

2024-02-27 15:35 UTC, Yang-Pi approved these changes

2024-03-06 10:37 UTC, merged