Add database
adrizhinskaya/java-filmorate pull request #7
Opened 2024-04-05 21:35 UTC by adrizhinskaya

Добавлены новые сущности: Genre и Mpa.
Создана база данных. 
Написаны интеграционные тесты. Они закомментированы потому что работают по отдельности, но не работают вместе. Позже будет разбираться на вебинаре.

2024-04-06 22:11 UTC, Yang-Pi requested changes
Общий комментарий: добавь логирование как для каки-то исключительных ситуаций, так и для обычного прохождения запроса вроде "создан фильм id"

2024-04-06 22:11 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbRepository.java
> +                jdbcTemplate.update(sqlQuery1, id, g.getId());
Сейчас тебе приходится делать N запросов к бд, чтобы обновить N записей - но можно сделать всего 1 запрос, если использовать jdbcTemplate.batchUpdate
https://www.baeldung.com/spring-jdbc-batch-inserts

2024-04-07 17:54 UTC, Yang-Pi requested changes

2024-04-07 17:54 UTC, Yang-Pi commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +//package ru.yandex.practicum.filmorate.controller;
Нужно что-то сделать с этими тестами

2024-04-07 18:31 UTC, adrizhinskaya commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +//package ru.yandex.practicum.filmorate.controller;
Я их удаляю, надеюсь вы клоните к этому)

2024-04-07 20:09 UTC, Yang-Pi approved these changes

2024-04-08 13:55 UTC, merged